"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 3.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
from django.utils.translation import ugettext_lazy as _

# import ldap
# from django_auth_ldap.config import LDAPSearch, ActiveDirectoryGroupType, GroupOfNamesType

# AD_DNS_NAME = 'zdc.ols'
# AD_LDAP_PORT = 389  # No-SSL
# # AD_LDAP_PORT = 636  # SSL
# AD_LDAP_URL = 'ldap://%s:%s' % (AD_DNS_NAME, AD_LDAP_PORT)  # No-SSL
# # AD_LDAP_URL = 'ldaps://%s:%s' % (AD_DNS_NAME, AD_LDAP_PORT)  # SSL
# AD_SEARCH_DN = 'dc=zdc,dc=ols'
# AD_NT4_DOMAIN = 'ad01'
# AD_SEARCH_FIELDS = ['mail', 'givenName', 'sn', 'sAMAccountName', 'memberOf']
# AD_MEMBERSHIP_ADMIN = ['django-admins']  # this ad group gets superuser status in django
# # only members of this group can access
# AD_MEMBERSHIP_REQ = AD_MEMBERSHIP_ADMIN + ['Group1',
#                                            'Group2',
#                                            'Group3']
#
# # AD_CERT_FILE = '/path/to/ca/cert'  # this is the certificate of the Certificate Authority issuing your DCs cert
# AD_DEBUG = True  # Set to false for prod, Slows things down A LOT
# AD_DEBUG_FILE = '/tmp/ldap.debug'

# AUTH_LDAP_SERVER_URI = 'ldap://192.168.1.7:389'
# AUTH_LDAP_ALWAYS_UPDATE_USER = True
# AUTH_LDAP_BIND_DN = "CN=bind,CN=Users,DC=zdc,DC=ols"
# AUTH_LDAP_BIND_PASSWORD = "Singapur@12"
# AUTH_LDAP_USER_SEARCH = LDAPSearch(
#     "DC=zdc,DC=ols", ldap.SCOPE_SUBTREE, '(sAMAccountName=%(user)s)',
# )
#
# AUTH_LDAP_USER_ATTR_MAP = {
#     "username": "sAMAccountName",
#     "first_name": "givenName",
#     "last_name": "sn",
#     "email": "mail",
# }
#
# AUTH_LDAP_GROUP_SEARCH = LDAPSearch(
#     "DC=zdc,DC=ols", ldap.SCOPE_SUBTREE, '(objectCategory=Group)',
# )
# AUTH_LDAP_GROUP_TYPE = ActiveDirectoryGroupType(name_attr="cn")
# AUTH_LDAP_USER_FLAGS_BY_GROUP = {
#     "is_superuser": 'CN=django-admins,CN=Users,DC=zdc,DC=ols',
#     "is_staff": 'CN=django-admins,CN=Users,DC=zdc,DC=ols',
# }
# AUTH_LDAP_FIND_GROUP_PERMS = True
# AUTH_LDAP_CACHE_GROUPS = True
# AUTH_LDAP_GROUP_CACHE_TIMEOUT = 1
# AUTH_LDAP_CONNECTION_OPTIONS = {
#     ldap.OPT_REFERRALS: 0,
# }
#
# AUTHENTICATION_BACKENDS = [
#     'django_auth_ldap.backend.LDAPBackend',
#     'django.contrib.auth.backends.ModelBackend',
# ]

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# 'ib55sf@3pg+r20-woea)jdy+@n^3pv@shf$jw#qbj)30x(8qq!'
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'ib55sf@3pg+r20-woea)jdy+@n^3pv@shf$jw#qbj)30x(8qq!')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', '') != 'False'

ALLOWED_HOSTS = ['172.23.96.55', '127.0.0.1', 'localhost']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'catalog',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGES = (
    ('pl', _('Polski')),
    ('en', _('English')),
)

LANGUAGE_CODE = 'pl'

LOCALE_PATHS = (
    os.path.join(BASE_DIR, 'locale'),
)

TIME_ZONE = 'Europe/Warsaw'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

LOGIN_REDIRECT_URL = '/catalog/'

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
